[build]
    functions = "functions"

[dev]
    autoLaunch = false

[[redirects]]
    from = "/"
    to = "/.netlify/functions/info"
    status = 200

[[redirects]]
    from = "/*"
    to = "/.netlify/functions/:splat"
    status = 200
